### PR TITLE
kind v0.9.0

### PR DESCRIPTION
**Pull request by bacongobbler**
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

**Comment by bacongobbler** [comment]
looks like this is blocked until #24 has been merged. 🐼

**Comment by alexellis** [comment]
Hi @bacongobbler we are wanting to use your action in OpenFaaS, but need a newer version of KinD than 1.17, can you make any suggestions on what we could do? Is there anything left that needs to be done to get #24 merged? Can we help in some way?

**Comment by bacongobbler** [comment]
Not my project; I’m just submitting a PR here.

**Comment by alexellis** [comment]
No worries.

It seems like it's possible to override the version and image which appears to work OK for us in the meantime.

**Comment by radu-matei** [comment]
I am so sorry I missed this PR, @bacongobbler!
Could you please rebase against the latest changes?

**Comment by bacongobbler** [comment]
certainly!

**Comment by bacongobbler** [comment]
done

**Review by radu-matei — APPROVED** [review]

**Pull request merged**
